### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by hunt3r** [EGWeeks/AMAPDFtoJSONParser#1]
I actually went ahead and wrote this in Python, I also wrote one to parse the hideously disgusting "Individual Lap Times" files for the practice sessions, which is really what I needed. Would love to chat sometime about where you were headed with this project.

Chris

**Comment by EGWeeks** [comment]
This repo hasn't required much maintenance because the PDF format for the results has not changed in years. There are a few races the results were posted differently, such as triple crown formats.

I am always willing to chat about moto and code. Email is on my profile.
